[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "credentials"
    name = "Credentials"
    url = "/about/"
    weight = 2
