# baseURL = "https://ahmedsblog.netlify.app//"
languageCode = "en-us"
title = "My Personal Blog"
theme = "PaperMod"

[params]
  author = "Ahmed Rashid" # Author name for metadata
  defaultTheme = "dark" # Default Theme (I personally prefer dark mode) 
  showReadingTime = true # Show estimated reading time in posts
  showCodeCopyButtons = true # Add a copy-to-clipboard button to code blocks.
  ShowPostNavLinks = true # shows navigation links (Prev/Next) at the bottom of posts
  ShowShareButtons = true 
  ShowBreadCrumbs = true
  ShowToc = true
  [params.homeInfoParams]
    Title = "Hello, I'm Your Name 👋"
    Content = "Welcome to my website. I'm a developer, writer, and enthusiast."

[menu]
  [[menu.main]]
    identifier = "home" # Identifier for the menu item (used internally)
    name = "Home" # Display name for the menu item
    url = "/" # relative URL relative to content root
    weight = 1 # Weight determines the order of the menu items (lower weight appears first)

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 3
